services:
  backend:
    container_name: backend_url_shortener
    build: ./backend/
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./backend/app:/app:rw
      - /app/node_modules
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is missing}
      POSTGRES_USER: ${POSTGRES_USER:? POSTGRES_USER is missing}
      POSTGRES_DB: ${POSTGRES_DB:? POSTGRES_DB is missing}
    ports:
      - "5432:5432"
    restart: unless-stopped
